## Requirements
# [Homebrew](https://github.com/Homebrew/brew) - dependencies
# [Cask](https://github.com/Homebrew/homebrew-cask) - mac applications
# [mas-cli](brew install mas) - Mac App Store applications
# [Visual Studio Code](https://code.visualstudio.com/) - VS Code extensions

tap "homebrew/bundle"
tap "homebrew/services"
brew "pycparser"
brew "cffi"
brew "docutils"
brew "python@3.11"
brew "awscli"
brew "chroma"
brew "docker", link: false
brew "icu4c"
brew "git"
brew "git-flow-avh"
brew "jq"
brew "node@18", link: true
brew "virtualenv"
brew "virtualenvwrapper"
brew "zsh"
cask "1password"
cask "arc"
cask "docker"
cask "linear-linear"
cask "notion"
cask "pgadmin4"
cask "readdle-spark"
cask "slack"
cask "visual-studio-code"
cask "whatsapp"
cask "zoom"
vscode "dbaeumer.vscode-eslint"
vscode "eamodio.gitlens"
vscode "esbenp.prettier-vscode"
vscode "GitHub.codespaces"
vscode "GitHub.copilot"
vscode "GitHub.copilot-chat"
vscode "GitHub.vscode-pull-request-github"
vscode "Gruntfuggly.todo-tree"
vscode "linear.linear-connect"
vscode "linear.linear-open-issue"
vscode "marp-team.marp-vscode"
vscode "ms-python.python"
vscode "ms-python.vscode-pylance"
vscode "ms-vscode.sublime-keybindings"
vscode "ms-vscode.vscode-typescript-next"
vscode "Shopify.theme-check-vscode"
vscode "thebearingedge.vscode-sql-lit"
vscode "WallabyJs.quokka-vscode"
vscode "ziyasal.vscode-open-in-github"
